window.ERITHREADS_BOOKS = {
    english: [
        "100 years of Solitude",
        "1Q84 - Haruki Murakami",
        "1984",
        "A Man Called Ove",
        "A Streetcar Named Desire - Tennessee Williams",
        "A Study in Scarlet, Arthur Conan Doyle",
        "A Thousand Splendid Suns",
        "A walk to remember",
        "Agatha Christie Omnibus",
        "Alice's Adventures in Wonderland",
        "All the Light We Cannot See",
        "And the Mountains Echoed",
        "And Then There Were None",
        "Animal Farm",
        "Anna Karenina",
        "Aristotle and Dante Discover the Secrets of the Universe",
        "Atonement - Ian McEwan",
        "Ayako",
        "Becoming",
        "Born a Crime",
        "Brave New World, Aldous Huxley",
        "Bridgerton",
        "Call me by your name",
        "Call of the Wild by Jack London",
        "Cat's Cradle, Kurt Vonnegut",
        "Chibineko Kitchen",
        "Chicken with Plums",
        "Chronicles of Narnia",
        "Cloud Atlas, David Mitchell",
        "Collected Poems - Sylvia Plath",
        "Crime and Punishment, Fyodor Dostoevsky",
        "Delhi is not far",
        "Diary of a Young Girl",
        "Dune",
        "Eat, pray, love",
        "Eleanor Oliphant Is Completely Fine",
        "Fahrenheit 451",
        "Fear and loathing in La Liga",
        "Five feet apart",
        "Follow My Tears, the Policeman Said, Philip K. Dick",
        "Forty Rules of Love - Elif Shafak",
        "Foundation, Isaac Assimov",
        "Frankenstein",
        "God Emperor of Dune, Frank Herbert",
        "Great Expectations",
        "Handmaid’s Tale",
        "Happy Prince",
        "Harry Potter and the Chamber of Secrets",
        "Harry Potter and the Deathly Hallows",
        "Harry Potter and the Goblet of Fire",
        "Harry Potter and the Half-Blood Prince",
        "Harry Potter and the Order of the Phoenix",
        "Harry Potter and the Philosopher's Stone",
        "Harry Potter and the Prisoner of Azkaban",
        "Heartstopper",
        "How We Disappeared - Jing Jing Lee",
        "How to kill your family",
        "Human Acts - Han Kang",
        "Hungry Tide",
        "It Ends With Us",
        "Jane Eyre",
        "Journey to the Center of the Earth",
        "Kabul beauty school",
        "Kafan, Munshi Premchand",
        "Kim Ji-Young, Born 1982 - Cho Nam Joo",
        "Kingdom’s End - Sadat Hasan Manto",
        "Laburnum for My Head - Temsula Ao",
        "Left Hand of Darkness, Ursula K Le Guin",
        "Les Miserables, Victor Hugo",
        "Letters to Juliet",
        "Liberation of Sita - Volga",
        "Lifting the Veil - Ismat Chughtai",
        "Lion Women of Tehran",
        "Little Fires Everywhere",
        "Lord of the Flies, William Golding",
        "Macbeth",
        "Maus",
        "Me Before You",
        "Memoirs of a Geisha",
        "Mo Dao Zu Shi - Mo Xiang Tong Xiu",
        "Mortal Instruments - city of bones",
        "Mother Mary Comes to Me",
        "Murder on the Orient Express",
        "My Dark Venessa",
        "Mythos",
        "Nutmeg's Curse.",
        "On Earth We are Briefly Gorgeous - Ocean Vuong",
        "One Hundred Years of Solitude",
        "P.S I love you",
        "Pachinko - Min Jin Le",
        "Penelopiad - Margaret Atwood",
        "Percy Jackson",
        "Perfume, Patrick Suskind",
        "Persepolis - Marjane Satrapi",
        "Peter Pan",
        "Pride and Prejudice",
        "Project Hail Mary, Andy Weir",
        "Prophet Song- Paul Lynch",
        "Rebecca",
        "Red, white, and royal blue",
        "Robinson Crusoe",
        "Sapiens a brief history of humankind",
        "Shadow and bones",
        "Sharp objects",
        "Sherlock Holmes",
        "Silver lining playbook",
        "Six of Crows",
        "Stranger in Strange Land, Robert A. Heinlein",
        "Sybil, Flora Rheta Schreiber",
        "Tender is the Flesh, Agustina Bazterrica",
        "Territory of Light - Yuko Tsushima",
        "The Adventures of Huckleberry Finn",
        "The Adventures of Tom Sawyer",
        "The Bell Jar",
        "The Bhagavad Gita",
        "The Book Thief",
        "The Boy, the Mole, the Fox and the Horse",
        "The Catcher in the Rye",
        "The Chocolate War, Robert Cormier",
        "The Color Purple",
        "The Count of Monte Cristo",
        "The Da Vinci Code",
        "The Dispossessed, ...",
        "The Emperor of All Maladies",
        "The Fountains of Paradise, Arthus C. Clarke",
        "The Girl with the Dragon Tattoo",
        "The God of Small Things - Arundhati Roy",
        "The Great Gatsby",
        "The Hobbit",
        "The House in the Cerulean Sea",
        "The House of the Spirits",
        "The Hunger Games",
        "The Kite Runner",
        "The Last Queen",
        "The Lord of the Rings",
        "The lost apothecary",
        "The Lost Symbol, Dan Brown",
        "The love hypothesis",
        "The Man in the High Castle, ...",
        "The Memory Police, Yoko Ogawa",
        "The Midnight Library - Matt Haig",
        "The Murder of Roger Ackroyd",
        "The Mysterious Affair at Styles",
        "The Mysterious Island, Jules Verne",
        "The Naked Sun",
        "The Nightingale",
        "The Origin, Irving Stone",
        "The Palace of Illusions",
        "The perks of being a wallflower",
        "The Picture of Dorian Gray",
        "The Sandman series",
        "The Scarlet Pimpernel, Baroness Orczy",
        "The Seven Husbands of Evelyn Hugo",
        "The Silent Patient",
        "The Song of Achilles",
        "The Stationery Shop of Tehran",
        "The Stormlight Archive",
        "The Successor, Ismail Kadare",
        "The sun is also a star",
        "The Tattooist of Auschwitz",
        "The Three Musketeers",
        "The Time Machine, H. G.Wells",
        "The Vegetarian - Han Kang",
        "The White Tiger",
        "The woman in the window",
        "The little prince",
        "Three Men in a Boat, Jerome K Jerome",
        "To Kill a Mockingbird",
        "To all the boys I’ve loved before",
        "Train to Pakistan",
        "Treasure Island",
        "Twisted Games",
        "Twisted Hate",
        "Twisted Lies",
        "Twisted Love",
        "Twilight",
        "Uzumaki - Junji Ito",
        "Watchmen",
        "White Fang by Jack London",
        "Wings of Fire",
        "Wonder",
        "Wuthering Heights"
    ],
    bengali: [
        "আগুনপাখি - হাসান আজিজুল হক",
        "আবোল তাবোল - সুকুমার রায়",
        "আলোর গন্ধ - স্মরণজিৎ চক্রবর্তী",
        "ইতি তোমার মা",
        "ইতি তোমার মা - সঞ্জীব চট্টোপাধ্যায়",
        "ইউক্রেনের লোককথা",
        "ঐতিহাসিক কাহিনী সমগ্র - শরদিন্দু বন্দ্যোপাধ্যায়",
        "ঐতিহাসিক কাহিনী সমগ্র - শরদিন্দু বন্দ্যোপাধ্যায়",
        "কাকতাড়ুয়া - সায়ক আমান",
        "কথামৃত",
        "কথামানবী - মল্লিকা সেনগুপ্ত",
        "কালবেলা - সমরেশ মজুমদার",
        "কালবেলা - সমরেশ মজুমদার",
        "কালবেলা, সমরেশ মজুমদার",
        "গীতাঞ্জলি",
        "গল্প 101 - সত্যজিৎ রায়",
        "গল্পগুচ্ছ",
        "গল্পগুচ্ছ - রবীন্দ্রনাথ ঠাকুর",
        "চাঁদের পাহাড় - বিভূতিভূষণ বন্দ্যোপাধ্যায়",
        "চন্দ্রমল্লিকা ও প্রাসঙ্গিক প্রবন্ধ",
        "জলেশ্বরী",
        "তারানাথ তান্ত্রিক - বিভূতিভূষণ বন্দ্যোপাধ্যায়",
        "তারই কিছু রং- জয়দীপ ঘোষ",
        "তোত্তো-চান",
        "দত্তা, শরৎ চন্দ্র চট্টোপাধ্যায়",
        "দোজখ্নামা - রবিশঙ্কর বল",
        "দেবযান",
        "ধুলা মাটির বাউল",
        "ন হন্যতে",
        "নীল পাহাড়",
        "পিকুর ডায়েরি, সত্যজিৎ রায়",
        "প্রোফেসর শঙ্কু - সত্যজিৎ রায়",
        "ফেলুদা সমগ্র - সত্যজিৎ রায়",
        "বঙ্কিম উপন্যাস সমগ্র - বঙ্কিমচন্দ্র চট্টোপাধ্যায়",
        "বঙ্কিম উপন্যাস সমগ্র - বঙ্কিমচন্দ্র চট্টোপাধ্যায়",
        "ব্যোমকেশ সমগ্র - শরদিন্দু বন্দ্যোপাধ্যায়",
        "বিশ্বাসঘাতক - নারায়ণ সান্যাল",
        "ভ্রমরাক্ষী",
        "মোল্লা নাসিরুদ্দিন",
        "রাজকাহিনী",
        "সত্যবতী ট্রিলজি - আশাপূর্ণা দেবী",
        "সীতা থেকে শুরু - নবনীতা দেব সেন",
        "সুকুমার সমগ্র",
        "সেই সময়",
        "সেই সময় - সুনীল গঙ্গোপাধ্যায়"
    ],
    colors: [
        "Red",
        "Blue",
        "Green"
    ],
    shelfTypes: [
        "3-Shelf",
        "4-Shelf",
        "6-Shelf"
    ]
};